export { VerificationMethodSelection } from './VerificationMethodSelection'
export { CompanySearchStep } from './CompanySearchStep'
export { CompanyEmailStep } from './CompanyEmailStep'
export { OTPVerificationStep } from './OTPVerificationStep'
export { OTPVerificationModal } from './OTPVerificationModal'
export { IDCardUploadStep } from './IDCardUploadStep'
export { VerificationStatusBanner, type VerificationStatus } from './VerificationStatusBanner'
export { VerificationSuccessModal } from './VerificationSuccessModal'

// Wrapper components for onboarding integration
export { VerificationMethodSelectionWrapper } from './VerificationMethodSelectionWrapper'
export { CompanySearchStepWrapper } from './CompanySearchStepWrapper'
export { CompanyEmailStepWrapper } from './CompanyEmailStepWrapper'
export { OTPVerificationStepWrapper } from './OTPVerificationStepWrapper'
export { IDCardUploadStepWrapper } from './IDCardUploadStepWrapper'
