[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "python start_with_migrations.py"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
