"""Add referral requests table

Revision ID: 004
Revises: 003
Create Date: 2023-10-26 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '004'
down_revision = '003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referral_requests',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('job_id', sa.Integer(), nullable=False),
        sa.Column('employee_id', sa.Integer(), nullable=False),
        sa.Column('jobseeker_id', sa.Integer(), nullable=False),
        sa.Column('jobseeker_name', sa.String(), nullable=False),
        sa.Column('jobseeker_email', sa.String(), nullable=False),
        sa.Column('jobseeker_phone', sa.String(), nullable=True),
        sa.Column('linkedin_url', sa.String(), nullable=True),
        sa.Column('resume_filename', sa.String(), nullable=True),
        sa.Column('resume_file_path', sa.String(), nullable=True),
        sa.Column('resume_file_size', sa.Integer(), nullable=True),
        sa.Column('resume_mime_type', sa.String(), nullable=True),
        sa.Column('personal_note', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('priority', sa.String(), nullable=False),
        sa.Column('employee_response', sa.String(), nullable=True),
        sa.Column('employee_notes', sa.String(), nullable=True),
        sa.Column('responded_at', sa.DateTime(), nullable=True),
        sa.Column('request_metadata', sa.JSON(), nullable=True),
        sa.Column('viewed_by_employee', sa.Boolean(), nullable=False),
        sa.Column('viewed_at', sa.DateTime(), nullable=True),
        sa.Column('last_activity', sa.DateTime(), nullable=True),
        sa.Column('notification_sent', sa.Boolean(), nullable=False),
        sa.Column('notification_sent_at', sa.DateTime(), nullable=True),
        sa.Column('reminder_sent', sa.Boolean(), nullable=False),
        sa.Column('reminder_sent_at', sa.DateTime(), nullable=True),
        sa.Column('response_time_hours', sa.Float(), nullable=True),
        sa.Column('outcome', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
        sa.ForeignKeyConstraint(['jobseeker_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_requests_employee_id'), 'referral_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_referral_requests_job_id'), 'referral_requests', ['job_id'], unique=False)
    op.create_index(op.f('ix_referral_requests_jobseeker_id'), 'referral_requests', ['jobseeker_id'], unique=False)
    op.create_index(op.f('ix_referral_requests_jobseeker_email'), 'referral_requests', ['jobseeker_email'], unique=False)
    op.create_index(op.f('ix_referral_requests_status'), 'referral_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referral_requests_status'), table_name='referral_requests')
    op.drop_index(op.f('ix_referral_requests_jobseeker_email'), table_name='referral_requests')
    op.drop_index(op.f('ix_referral_requests_jobseeker_id'), table_name='referral_requests')
    op.drop_index(op.f('ix_referral_requests_job_id'), table_name='referral_requests')
    op.drop_index(op.f('ix_referral_requests_employee_id'), table_name='referral_requests')
    op.drop_table('referral_requests')
    # ### end Alembic commands ###
